### PR TITLE
No installation. Simply click 'edit', he or she could start play with the examples in the browser

### PR DESCRIPTION
**Pull request by chfw**
Use case:

screen shot 2017-10-25 at 22 07 27

What happens if user clicks:

screen shot 2017-10-25 at 22 09 16

And click 'Run':

screen shot 2017-10-25 at 22 11 35

Wow, the magic happens: the bar3d could be full screen and the page has been drawn fully

screen shot 2017-10-25 at 22 12 38

Baseline is pyecharts 0.2.6.

Finally, thank for open source the site so that I can modify it.

### CODE REVIEW

**Comment by chenjiandongx** [comment]
@chfw 好的地方在于用户可以在线体验，不好的地方就是现在所有的 `chart`.py 文件都是相对独立的，以后管理起来可能比较麻烦

**Comment by chfw** [comment]
hold on. will address management issue with next wave of changes.

**Comment by chfw** [comment]
screen shot 2017-10-26 at 20 51 07

**Comment by chfw** [comment]
But TREE_MAP, ENERGY and WEIBO were permanently moved out from constants.py, because they are too big in size. It will take long to be downloaded, affecting user browsing experience.

**Comment by chfw** [comment]
Here is the [edit in browser](https://chfw.github.io/pyecharts.js-app/#https://raw.githubusercontent.com/chfw/pyecharts-app/master/app/charts/bar3d.py) link for your preview.

**Comment by chenjiandongx** [comment]
@chfw 没问题了

**Comment by chenjiandongx** [comment]
@chfw http://pyecharts.herokuapp.com  同步更新了

**Pull request merged**
